version: "3.4"

volumes:
  db:

networks:
  dbnet:

services:
  database:
    image: mariadb
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Abc123456
      MYSQL_USER: meethut
      MYSQL_PASSWORD: Abc123456
      MYSQL_DATABASE: meethut
    networks:
      - dbnet

  frontend:
    build:
      context: ./MeetHut.Backend/ClientApp
      dockerfile: Dockerfile
    networks:
      - dbnet
    volumes:
      - ./MeetHut.Backend/ClientApp:/app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meethut-backend
    depends_on:
      - database
      - frontend
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5001:5001"
    environment:
      - DBHOST=database
    networks:
      - dbnet
    volumes:
      - ./:/src

  adminer:
    image: adminer
    ports:
      - "127.0.0.1:81:8080"
    networks:
      - dbnet
    depends_on:
      - database
