name: Backend Build and Test

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Install deps
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
