name: Client Build and Test

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      working-directory: ./MeetHut.Backend/ClientApp
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install deps
        run: npm i
        working-directory: ${{env.working-directory}}
      - name: Build
        run: npm run build:ci
        working-directory: ${{env.working-directory}}
      - name: Test
        run: npm run test:ci
        working-directory: ${{env.working-directory}}
        env:
          CI: true
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: MeetHut.Backend/ClientApp/dist
      - name: Archive code coverage
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          path: MeetHut.Backend/ClientApp/coverage
